services:

  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    networks:
      - apprise
    ports:
      - 8005:8000
    volumes:
      - ./apprise_config:/config
    labels:
      homepage.group: Update & Monitor
      homepage.name: Apprise
      homepage.icon: mdi-bullhorn-outline.svg
      homepage.href: http://localhost:8005
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped

networks:
  apprise:
    external: true
  homepage-net:
    external: true
